name: zoumayuetan
on:
  workflow_dispatch:
  schedule:
    - cron: '12 3/6 * * *'

jobs:  # 8302
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zoumayuetan
        env:
          yxf8649: ${{ secrets.yxf8649 }}
        run: |
          echo $yxf8649 | jq -r .xi20687 | /bin/bash
          echo $s958 | jq -r .fp56005 | /bin/bash

